name: 🚀 Deploy Syrup to VPS
on:
  push:
    branches: [master]          # 👉 deploy only when master is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ── 1.  Install Node and cache npm ────────────────────────────────
      - uses: actions/setup-node@v4
        with:
          node-version: 18        # use any version you need
          cache: npm

      # ── 2.  SSH into the VPS and run everything there ────────────────
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 209.74.81.251          # ← your new VPS IP
          username: root               # or ftpuser if you prefer
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22022
          script: |
            set -e

            # 1. Clone repo first time, otherwise pull latest ------------
            if [ ! -d /var/www/syrup/.git ]; then
              mkdir -p /var/www
              cd /var/www
              git clone git@github.com:Waseem7771/Syrup.git syrup
            fi

            cd /var/www/syrup
            git fetch origin master
            git reset --hard origin/master      # clean, exact copy

            # 2. Install / update dependencies ---------------------------
            npm ci

            # 3. Build Vite front-end ------------------------------------
            npm run build                       # creates dist/

            # 4. Ensure serve & pm2 exist --------------------------------
            if ! command -v pm2 >/dev/null 2>&1; then
              npm i -g pm2 serve
            fi

            # 5. Start (or reload) static server via PM2 -----------------
            if pm2 list | grep -q syrup-site; then
              pm2 delete syrup-site
            fi
            pm2 start serve --name syrup-site -- -s dist -l 0.0.0.0:3000
            pm2 save                            # survive reboots
