name: Build & Deploy to Spaceship VM

on:
  push:
    branches: [main]          # adjust if you deploy from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) Check out code
    - uses: actions/checkout@v4

    # 2) Set up Node 20 (LTS) :contentReference[oaicite:0]{index=0}
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'          # speeds up installs

    # 3) Install dependencies & build
    - run: npm ci             # reproducible install
    - run: npm run build      # vite build -> dist/

    # 4) Copy dist/ to the server (appleboy/scp-action) :contentReference[oaicite:1]{index=1}
    - name: Upload files via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host:      ${{ secrets.SSH_HOST }}
        username:  ${{ secrets.SSH_USER }}
        key:       ${{ secrets.SSH_PRIVATE_KEY }}
        port:      ${{ secrets.SSH_PORT }}
        source:    "dist/*"
        target:    "/home/ftpuser/app/dist"   # pick any directory you own

    # 5) Restart or start the site with PM2 over SSH (appleboy/ssh-action) :contentReference[oaicite:2]{index=2}
    - name: Reload PM2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host:      ${{ secrets.SSH_HOST }}
        username:  ${{ secrets.SSH_USER }}
        key:       ${{ secrets.SSH_PRIVATE_KEY }}
        port:      ${{ secrets.SSH_PORT }}
        script: |
          #!/bin/bash
          pm2 reload syrup \
            || pm2 start serve --name syrup -- -s /home/ftpuser/app/dist -l 0.0.0.0:3000
